version: '3.1'
services:
  #Nginx Service
   nginx-lb:
     image: nginx:latest
     volumes:
       - ./lb/nginx.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - webserver1
       - webserver2
     ports:
       - "80:80"
     networks:
       - webapp
   webserver1:
     image: nginx:latest
     container_name: webserver1
     restart: unless-stopped
     ports:
       - "8081:80"
     volumes:
      - ./web1/index.html:/usr/share/nginx/html/index.html
     networks:
       - webapp
   webserver2:
     image: nginx:latest
     container_name: webserver2
     restart: unless-stopped
     ports:
       - "8082:80"
     volumes:
      - ./web2/data/index.html:/usr/share/nginx/html/index.html
     networks:
       - webapp

networks:
   webapp:
